// <auto-generated />
namespace gestionDePiletaSportClub.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class clasesCovid20192020Fri : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(clasesCovid20192020Fri));
        
        string IMigrationMetadata.Id
        {
            get { return "202012142315080_clasesCovid2019-2020-Fri"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
